export const BLOOD_TYPES = ['A', 'B', 'O', 'AB'];
export const FACTIONS = { CENTER: 'center', KARTEIN: 'kartein', NEUTRAL: 'neutral' };
export const RARITIES = { COMMON: 'common', UNCOMMON: 'uncommon', RARE: 'rare', LEGENDARY: 'legendary' };

export const SENSE_TYPES = {
  예감: { type: 'buff', category: '촉', counters: '혈향', icon: '👁' },
  직감: { type: 'action', category: '촉', counters: '혈압', icon: '⚡' },
  감응: { type: 'passive', category: '촉', counters: '혈유', icon: '🔗' },
  혈각: { type: 'action', category: '촉', counters: '혈식', icon: '🩸' },
  투지: { type: 'buff', category: '촉', counters: '혈기', icon: '🔥' },
  공감: { type: 'buff', category: '촉', counters: '혈맹', icon: '💛' },
  혈압: { type: 'action', category: '혈', counteredBy: '직감', icon: '👊' },
  혈향: { type: 'passive', category: '혈', counteredBy: '예감', icon: '🌬' },
  혈맹: { type: 'buff', category: '혈', counteredBy: '공감', icon: '⛓' },
  혈식: { type: 'action', category: '혈', counteredBy: '혈각', icon: '🌑' },
  혈기: { type: 'passive', category: '혈', counteredBy: '투지', icon: '💀' },
  혈유: { type: 'action', category: '혈', counteredBy: '감응', icon: '🫦' },
};

export const CHARACTER_MBTI = {
  'park-harin': 'ENTJ',
  'kim-doyun': 'ISFP',
  'lee-seoyeon': 'INTP',
  'kartein-duke': 'INTJ',
  'choi-minseo': 'ISTJ',
  'jung-woojin': 'ESTP',
  'viktor-hessen': 'ISTP',
  'han-soyul': 'ISFJ',
  'nigel-crowe': 'INTP',
  'yun-chaea': 'ENFP',
  'shin-yujin': 'INFJ',
  'oh-taehyun': 'ENTP',
  'yang-mira': 'ENFJ',
  'elena-morgan': 'ENFP',
  'sergei-volkov': 'ISTJ',
  'isadora-kartein': 'INFJ',
  'dimitri-rad': 'ESTP',
  'park-eunji': 'ESFP',
  'jang-hyunwoo': 'ISTP',
  'kim-seoha': 'INFP',
  'kwon-jihye': 'ISTJ',
  'yoo-jaehwan': 'ESTJ',
  'song-minji': 'ISFJ',
  'nam-kihyun': 'ESTP',
  'baek-sujin': 'ENFJ',
  'cha-donghyuk': 'INTP',
  'im-yeji': 'INFP',
  'go-seungwoo': 'ENTJ',
  'hwang-nari': 'ESFP',
  'moon-taesik': 'ESTJ',
  'cecilia-kartein': 'ENFJ',
  'madeleine-voss': 'INTJ',
  'aldric-thorne': 'ENTJ',
  'otto-brandt': 'ESTJ',
  'kaspar-wren': 'ISFP',
  'nadia-petrova': 'ENTP',
  'lucien-deveraux': 'INFP',
  'marcus-vale': 'ESTP',
  'vivienne-la-croix': 'ENFJ',
  'nikolai-frost': 'ISTP',
  'yoo-minjae': 'ESFP',
  'bae-jongho': 'ESTJ',
  'hong-taejun': 'ESTP',
  'kang-mirae': 'INFJ',
  'seo-pilsung': 'ENTP',
  'won-hyunsoo': 'ISTP',
  'ryu-seungmin': 'ESFP',
  'jo-eunyoung': 'ENTJ',
  'priest-gabriel': 'INFJ',
  'commissioner-park': 'ENTJ',
};

export const CHARACTERS = [
  {
    id: 'park-harin',
    name: '박하린',
    title: '혈연센터장',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.RARE,
    role: 'support',
    cost: 4,
    power: 3,
    ability: { type: 'collect', value: 2, description: 'BP +2 수집. 배치 시 REP +5', onPlay: { rep: 5 } },
    sense: { name: '균형의 눈', baseType: '예감', power: 7, flavor: '피는 흘러야 한다 — 누구의 것이든.', effects: { onPlay: { sus: -3, rep: 3 }, onCollect: { rep: 1 } } },
    flavor: '밝은 미소 뒤의 차가운 계산',
    lore: '센터장 박하린은 모든 것을 알고 있다. 카르테인의 존재도, 그들이 원하는 것도. 하지만 그녀가 택한 건 폭로가 아닌 균형이었다. 피는 흘러야 한다 — 누구의 것이든. 그녀의 미소 뒤에는 서울의 밤을 지탱하는 차가운 계산이 있다.',
    portrait: 'assets/portraits/park-harin',
  },
  {
    id: 'kim-doyun',
    name: '김도윤',
    title: '신입 간호사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.COMMON,
    role: 'support',
    cost: 1,
    power: 1,
    ability: { type: 'collect', value: 1, description: 'BP +1 수집' },
    sense: { name: '첫날의 떨림', baseType: '직감', power: 2, flavor: '선배, 저 복도에서 뭔가 봤는데요...', effects: { onPlay: { sus: -1 }, onCollect: { rep: 1 } } },
    flavor: '순수한 열정, 위험한 무지',
    lore: '첫 출근날, 선배가 말했다. \'냉장고 온도만 잘 확인하면 돼.\' 김도윤은 고개를 끄덕였지만, 그날 밤 복도에서 마주친 은발의 남자는 분명 직원이 아니었다. 아직은 묻지 않기로 했다. 신입은 조용한 게 미덕이니까.',
    portrait: 'assets/portraits/kim-doyun',
  },
  {
    id: 'lee-seoyeon',
    name: '이서연',
    title: '베테랑 채혈사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 3,
    power: 2,
    ability: { type: 'collect', value: 3, description: 'BP +3 수집. SUS -2', onCollect: { sus: -2 } },
    sense: { name: '맥의 기억', baseType: '혈각', power: 4, flavor: '이 정맥... 체온이 너무 낮아.', effects: { onPlay: { sus: -2 }, onCollect: { rep: 1 } } },
    flavor: '의심의 눈초리, 완벽한 기술',
    lore: '10년간 수만 번의 채혈을 했다. 혈관의 떨림, 피부의 온기 — 이서연의 손끝은 거짓말을 하지 않는다. 그런데 최근 VIP 헌혈자들의 혈관은… 너무 차갑다. 체온이 35도 이하인 사람에게서 피를 뽑은 건 처음이었다.',
    portrait: 'assets/portraits/lee-seoyeon',
  },
  {
    id: 'kartein-duke',
    name: '카르테인 듀크',
    title: '혈액관리국장',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.LEGENDARY,
    role: 'breaker',
    cost: 7,
    power: 5,
    ability: { type: 'request_discount', value: 2, description: '의뢰 이행 비용 -2. 필드 시 SUS +5/턴', onField: { sus: 5 } },
    sense: { name: '만찬의 시간', baseType: '혈식', power: 10, flavor: '이 도시의 피를 확보하라 — 듀크 가문의 명령이다.', effects: { onPlay: { sus: 15, rep: -5, bp: -10 }, onField: { sus: 2, rep: -1 } } },
    flavor: '우아한 포식자',
    lore: '400년을 살았지만, 서울의 네온사인은 처음이다. 듀크 가문의 명령은 단순했다 — 이 도시의 피를 확보하라. 하지만 이곳의 센터장은 눈이 너무 날카롭고, 이 나라의 간호사들은 질문을 너무 많이 한다. 시간은 그의 편이지만, 이번만큼은 확신할 수 없었다.',
    portrait: 'assets/portraits/kartein-duke',
  },
  {
    id: 'choi-minseo',
    name: '최민서',
    title: '단골 헌혈자',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.COMMON,
    role: 'tank',
    cost: 1,
    power: 1,
    ability: { type: 'donate', value: 2, description: '혈액 카드 2장 생성' },
    sense: { name: '헌혈자의 감', baseType: '직감', power: 2, flavor: '나이 탓이겠지... 그렇겠지?', effects: { onPlay: { sus: -1 }, onCollect: { rep: 1 } } },
    flavor: '헌혈 300회의 사나이',
    lore: '300회 헌혈. 동네에서는 \'피의 영웅\'이라 부른다. 매달 센터에 오면 간호사들이 반겨주고, 주스와 쿠키가 기다린다. 최민서에게 헌혈은 삶의 일부다. 다만 요즘 헌혈 후 유난히 피곤한 게… 나이 탓이겠지.',
    portrait: 'assets/portraits/choi-minseo',
  },
  {
    id: 'jung-woojin',
    name: '정우진',
    title: '혈액운송기사',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.UNCOMMON,
    role: 'melee_dps',
    cost: 2,
    power: 2,
    ability: { type: 'transport', value: 1, description: '의뢰 이행 시 BP 보너스 +1' },
    sense: { name: '야로의 촉', baseType: '직감', power: 4, flavor: '이 길은... 오늘은 돌아가자.', effects: { onPlay: { sus: -2 }, onCollect: { rep: 1 } } },
    flavor: '새벽 4시의 특별 배송',
    lore: '밤 11시, 냉장 컨테이너를 싣고 서울을 달린다. 정우진은 내비게이션에 뜨지 않는 주소로 배달을 갈 때가 있다. 그 건물에는 간판도 없고, 받는 사람의 손은 항상 장갑을 끼고 있었다. 물어본 적은 없다 — 야간 수당이 두 배니까.',
    portrait: 'assets/portraits/jung-woojin',
  },
  {
    id: 'viktor-hessen',
    name: '빅토르 헤센',
    title: '카르테인 집사',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'tank',
    cost: 5,
    power: 3,
    ability: { type: 'convert', value: 1, description: '혈액 카드 1장을 아무 혈액형으로 변환' },
    sense: { name: '충복의 잔', baseType: '혈기', power: 6, flavor: '듀크 각하의 잔이 비는 일은 결코 없을 것입니다.', effects: { onPlay: { sus: 3 }, onField: { sus: 1, bp: -1 } } },
    flavor: '300년의 충성',
    lore: '빅토르 헤센은 카르테인 가문을 3대째 모시고 있다. 아니, 정확히는 5대째다 — 다만 인간의 기억으로는 3대가 한계일 뿐. 그의 충성은 계약이 아닌 피로 맺어졌고, 듀크 각하의 잔이 비는 일은 결코 없을 것이다.',
    portrait: 'assets/portraits/viktor-hessen',
  },
  {
    id: 'han-soyul',
    name: '한소율',
    title: '대학생 봉사자',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.COMMON,
    role: 'support',
    cost: 1,
    power: 1,
    ability: { type: 'reputation', value: 3, description: 'REP +3' },
    sense: { name: '셀카의 직감', baseType: '감응', power: 1, flavor: '좋아요 수가 말해주는 게 있어요.', effects: { onPlay: { rep: 1 } } },
    flavor: 'SNS 좋아요의 힘',
    lore: '봉사시간 채우려고 헌혈센터에 왔는데, 생각보다 분위기가 좋아서 매주 온다. 한소율은 셀카 찍고, 쿠키 먹고, SNS에 올린다. \'#헌혈스타그램 #생명나눔\'. 다만 지난주에 올린 사진 배경에 찍힌 그 남자… 왜 눈이 빛나 보이지?',
    portrait: 'assets/portraits/han-soyul',
  },
  {
    id: 'nigel-crowe',
    name: '나이젤 크로우',
    title: '야간 감사관',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'ranged_dps',
    cost: 4,
    power: 3,
    ability: { type: 'audit', value: 3, description: 'SUS -3. 이벤트 카드 1장 확인' },
    sense: { name: '장부의 칼', baseType: '혈기', power: 7, flavor: '이 장부의 행간을 읽을 줄 아는 자는 많지 않지.', effects: { onPlay: { sus: 3 }, onField: { sus: 1 } } },
    flavor: '장부에 숨긴 진실',
    lore: '밤 10시, 장부가 열린다. 나이젤 크로우의 만년필은 한 치의 오차도 허용하지 않는다. 혈액의 입출고, 온도 변화, 유통기한 — 모든 숫자가 그의 머릿속에 있다. 센터 직원들은 그를 두려워한다. 그의 감사에서 빠져나간 거짓말은 지난 200년간 단 하나도 없었으니까.',
    portrait: 'assets/portraits/nigel-crowe',
  },
  {
    id: 'yun-chaea',
    name: '윤채아',
    title: '혈액연구원',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 3,
    power: 2,
    ability: { type: 'research', value: 1, description: '혈액 카드 효율 +1 (이번 턴)' },
    sense: { name: '변이의 촉', baseType: '혈각', power: 4, flavor: '이 혈액 샘플... 분자 구조가 정상이 아니야.', effects: { onPlay: { sus: -2 }, onCollect: { rep: 1 } } },
    flavor: '데이터는 거짓말하지 않는다',
    lore: '시험관 속 혈액이 이상하다. 원심분리 후에도 응고되지 않는 샘플이 있다. 윤채아는 처음에 장비 오류를 의심했지만, 세 번째 실험에서 확신했다 — 이건 일반적인 인간의 피가 아니다. 보고서를 올릴까 망설이는 중이다.',
    portrait: 'assets/portraits/yun-chaea',
  },
  {
    id: 'shin-yujin',
    name: '신유진',
    title: '접수 담당자',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'support',
    cost: 2,
    power: 1,
    ability: { type: 'collect', value: 2, description: 'BP +2 수집. SUS -2', onCollect: { sus: -2 } },
    sense: { name: '얼굴의 진실', baseType: '감응', power: 4, flavor: '저 분... 접수할 때 눈을 못 마주치셨어요.', effects: { onPlay: { rep: 2 } } },
    flavor: '원칙대로 하겠습니다',
    lore: '접수대에서 보이는 것들이 있다. 신유진은 매일 수백 명의 얼굴을 확인한다. 신분증 사진과 실물이 일치하지 않는 사람들 — 10년 전 사진인데 한 살도 안 늙은 것 같은 사람들. 그녀는 조용히 리스트를 만들기 시작했다.',
    portrait: 'assets/portraits/shin-yujin',
  },
  {
    id: 'oh-taehyun',
    name: '오태현',
    title: '혈액분석사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 3,
    power: 2,
    ability: { type: 'collect', value: 2, description: 'BP +2 수집. REP +5', onCollect: { rep: 5 } },
    sense: { name: '이상 수치', baseType: '혈각', power: 4, flavor: '이 수치가 정상일 리 없어. 다시 분석해봐.', effects: { onPlay: { sus: -2 }, onCollect: { rep: 1 } } },
    flavor: '분석은 거짓을 허용하지 않는다',
    lore: '혈액 분석 결과지를 들여다보는 것이 오태현의 하루다. AB형, Rh-, 항체 패턴… 모든 것이 규칙적이어야 한다. 그런데 \'VIP-07\' 라벨이 붙은 샘플의 백혈구 수치는 의학 교과서를 벗어나 있었다. 상사에게 보고하자 돌아온 답은 \'무시해\'였다.',
    portrait: 'assets/portraits/oh-taehyun',
  },
  {
    id: 'yang-mira',
    name: '양미라',
    title: '헌혈 홍보대사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.RARE,
    role: 'battle_support',
    cost: 5,
    power: 3,
    ability: { type: 'donate', value: 3, description: '혈액 카드 3장 생성' },
    sense: { name: '카메라의 미소', baseType: '공감', power: 6, flavor: '진심은 렌즈를 통해서도 전해져요.', effects: { onPlay: { rep: 5 }, onField: { rep: 1 } } },
    flavor: '헌혈은 사랑입니다, 진심으로',
    lore: '카메라 앞에서 미소 짓는 것은 양미라의 직업이다. \'여러분의 한 방울이 생명을 살립니다!\' 하지만 헌혈 캠페인의 뒷면에서 그녀는 혈액 수급 보고서를 읽었고, 수치가 맞지 않는다는 걸 알았다. 기부되는 피보다 사라지는 피가 더 많다.',
    portrait: 'assets/portraits/yang-mira',
  },
  {
    id: 'elena-morgan',
    name: '엘레나 모르간',
    title: '야행성 수습생',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.UNCOMMON,
    role: 'melee_dps',
    cost: 2,
    power: 2,
    ability: { type: 'collect', value: 1, description: 'BP +1 수집' },
    sense: { name: '황혼의 적응', baseType: '혈향', power: 4, flavor: '냄새로 알 수 있어... 누가 O형인지.', effects: { onPlay: { sus: 1 }, onField: { sus: 1 } } },
    flavor: '낮에는 졸고, 밤에 일한다',
    lore: '카르테인 가문의 수습생이 된 지 3개월. 엘레나 모르간은 아직 햇빛이 그립다. 밤에만 일하고, 낮에는 자고, \'가문의 방식\'을 배운다. 선배들은 친절하지만, 그들의 눈빛에는 수백 년의 무게가 있다. 커피는 많이 마시는데, 식사는 본 적이 없다.',
    portrait: 'assets/portraits/elena-morgan',
  },
  {
    id: 'sergei-volkov',
    name: '세르게이 볼코프',
    title: '동유럽 연락관',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.UNCOMMON,
    role: 'tank',
    cost: 4,
    power: 3,
    ability: { type: 'collect', value: 3, description: 'BP +3 수집' },
    sense: { name: '철의 물류', baseType: '혈기', power: 4, flavor: '동유럽 루트는 내가 관리한다. 조용히.', effects: { onPlay: { sus: 2 }, onField: { sus: 1 } } },
    flavor: '동유럽 루트는 조용해야 해',
    lore: '모스크바에서 서울까지, 세르게이 볼코프가 움직이면 물류가 따라온다. 그는 말이 적고 행동이 빠르다. 동유럽의 \'혈액 네트워크\'를 관리하는 것이 그의 임무이며, 실패는 허용되지 않는다. 이어폰 너머의 명령은 항상 간결하다 — \'더 많이, 더 빨리.\'',
    portrait: 'assets/portraits/sergei-volkov',
  },
  {
    id: 'isadora-kartein',
    name: '이사도라 카르테인',
    title: '가문 장녀',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.LEGENDARY,
    role: 'breaker',
    cost: 8,
    power: 6,
    ability: { type: 'collect', value: 5, description: 'BP +5 수집. 필드 시 SUS +3/턴', onField: { sus: 3 } },
    sense: { name: '지배의 선언', baseType: '혈식', power: 9, flavor: '가문의 피는 속일 수 없다. 그리고 이 도시도.', effects: { onPlay: { sus: 12, rep: -3, bp: -8 }, onField: { sus: 2 } } },
    flavor: '가문의 피는 속일 수 없다',
    lore: '이사도라 카르테인. 그 이름만으로 방 안의 공기가 바뀐다. 가문의 장녀로서 수백 년의 무게를 어깨에 짊어진 그녀는 서울 작전의 최종 결정권자다. 아버지의 명령, 어머니의 기대, 동생의 반항 — 모든 것을 통제하면서도 그녀의 시선은 항상 센터장 박하린을 향해 있다. 위험한 존경일까, 아니면 전략적 관심일까.',
    portrait: 'assets/portraits/isadora-kartein',
  },
  {
    id: 'dimitri-rad',
    name: '디미트리 라드',
    title: '혈액 감정사',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'evasive_dps',
    cost: 5,
    power: 4,
    ability: { type: 'collect', value: 4, description: 'BP +4 수집. SUS -2', onCollect: { sus: -2 } },
    sense: { name: '미각의 경지', baseType: '혈향', power: 6, flavor: '보르도산 1847년... 아니, 이건 AB형 Rh-다.', effects: { onPlay: { sus: 2 }, onField: { sus: 1 } } },
    flavor: '보르도산 1847년, 최고의 빈티지',
    lore: '와인을 감정하듯 피를 감정한다. 디미트리 라드의 혀는 혈액의 출처, 건강 상태, 심지어 감정까지 읽어낸다. 그에게 피는 예술이다. 서울의 헌혈센터에서 확보한 샘플 중, 그는 \'걸작\'을 하나 발견했다. 희귀 혈액형 보유자 — 그 사람을 찾아야 한다.',
    portrait: 'assets/portraits/dimitri-rad',
  },
  {
    id: 'park-eunji',
    name: '박은지',
    title: '의대생 실습생',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.UNCOMMON,
    role: 'melee_dps',
    cost: 2,
    power: 1,
    ability: { type: 'donate', value: 2, description: '혈액 카드 2장 생성' },
    sense: { name: '호기심의 문', baseType: '직감', power: 4, flavor: '야간 처리량이 왜 이렇게 많죠?', effects: { onPlay: { sus: -2 }, onCollect: { rep: 1 } } },
    flavor: '실습이라면서 왜 이렇게 많이...',
    lore: '의대 실습으로 온 헌혈센터. 박은지는 교과서에서 배운 것과 현실이 다르다는 걸 깨달았다. 야간에만 들어오는 특별 혈액 주문, 잠긴 복도, 설명되지 않는 검사 프로토콜. 교수님은 \'질문하지 마\'라고 했지만, 그녀의 호기심은 이미 깨어났다.',
    portrait: 'assets/portraits/park-eunji',
  },
  {
    id: 'jang-hyunwoo',
    name: '장현우',
    title: '보건복지부 조사관',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 3,
    power: 2,
    ability: { type: 'reputation', value: 4, description: 'REP +4' },
    sense: { name: '감사의 눈', baseType: '예감', power: 4, flavor: '서류는 거짓말하지 않지만, 사람은 합니다.', effects: { onPlay: { sus: -2, rep: 2 } } },
    flavor: '규정을 따르면 아무 문제 없습니다',
    lore: '보건복지부에서 나온 조사관 장현우. 분기별 정기 감사가 그의 업무다. 서류는 완벽하고, 시설은 깨끗하다. 하지만 숫자가 이상하다 — 혈액 수급량과 병원 배분량 사이에 15%의 차이가 있다. 어디로 사라진 걸까. 상부에 보고했지만 \'처리 중\'이라는 답만 돌아온다.',
    portrait: 'assets/portraits/jang-hyunwoo',
  },
  {
    id: 'kim-seoha',
    name: '김서하',
    title: '의료 전문기자',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.RARE,
    role: 'battle_support',
    cost: 4,
    power: 3,
    ability: { type: 'reputation', value: 8, description: 'REP +8' },
    sense: { name: '펜의 직감', baseType: '직감', power: 6, flavor: '혈액 부족, 야간 배송, 유럽계 재단... 점이 연결되고 있다.', effects: { onPlay: { sus: -3 }, onCollect: { rep: 1 } } },
    flavor: '기사 한 줄이면 세상이 바뀐다',
    lore: '김서하의 취재 수첩에는 세 개의 키워드가 적혀 있다. \'혈액 부족\', \'야간 배송\', \'유럽계 재단\'. 점을 연결하면 그림이 보인다 — 하지만 기사를 쓸 때마다 편집장이 멈춘다. \'광고주 문제\'라고 한다. 그녀는 독립 매체로 옮길 준비를 하고 있다. 이 이야기는 반드시 세상에 나와야 한다.',
    portrait: 'assets/portraits/kim-seoha',
  },
  {
    id: 'kwon-jihye',
    name: '권지혜',
    title: '야간 경비원',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.COMMON,
    role: 'tank',
    cost: 2,
    power: 1,
    ability: { type: 'audit', value: 1, description: 'SUS -1. 이벤트 카드 1장 확인' },
    sense: { name: '야경(夜警)의 투지', baseType: '투지', power: 2, flavor: 'B2 카메라가 꺼졌다. 오늘은 내가 직접 본다.', effects: { onPlay: { rep: 1 }, onCollect: { rep: 1 } } },
    flavor: 'B2 복도의 진실을 찾아서',
    lore: '밤 근무는 조용하다. 권지혜는 그게 좋다. CCTV를 보고, 복도를 돌고, 문을 확인한다. 하지만 B2 복도의 카메라가 매일 새벽 2시에 꺼지는 건 정상이 아니다. 상사에게 물었더니 \'시스템 점검\'이라고 했다. 그녀는 다음 날부터 개인 카메라를 들고 순찰한다.',
    portrait: 'assets/portraits/kwon-jihye',
  },
  {
    id: 'yoo-jaehwan',
    name: '유재환',
    title: '시설관리 기사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.COMMON,
    role: 'tank',
    cost: 1,
    power: 1,
    ability: { type: 'reputation', value: 2, description: 'REP +2' },
    sense: { name: '오래된 배관', baseType: '투지', power: 2, flavor: '지하 3층 아래 배관은... 내가 설치한 게 아닌데.', effects: { onPlay: { rep: 1 }, onCollect: { rep: 1 } } },
    flavor: '20년간 센터의 모든 것을 고친 남자',
    lore: '보일러가 고장 나면 유재환이 온다. 전선이 끊어져도 유재환이 온다. 20년 동안 이 센터의 모든 배관과 전선을 만진 남자. 하지만 지하 3층 아래의 배관은 그가 설치한 것이 아니다. 누가, 언제 깔았는지 모른다. 그리고 그 파이프에서는 항상 미지근한 온기가 느껴진다.',
    portrait: 'assets/portraits/yoo-jaehwan',
  },
  {
    id: 'song-minji',
    name: '송민지',
    title: '혈액은행 사서',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.COMMON,
    role: 'support',
    cost: 2,
    power: 1,
    ability: { type: 'collect', value: 1, description: 'BP +1 수집. REP +2', onCollect: { rep: 2 } },
    sense: { name: '재고의 기억', baseType: '감응', power: 2, flavor: 'RhNull 혈액 2백이 사라졌어요. 반출 기록 없이요.', effects: { onPlay: { rep: 1 }, onField: { rep: 1 } } },
    flavor: '모든 혈액의 주소를 외우는 여자',
    lore: '혈액은행의 모든 혈액에는 주소가 있다. 송민지는 그 주소를 외우고 있다. A형 양성 320백, B형 음성 87백… 재고 목록은 그녀의 머릿속에 완벽하게 정리되어 있다. 그래서 알 수 있었다 — 어젯밤 반출 기록 없이 사라진 RhNull 혈액 2백의 행방을.',
    portrait: 'assets/portraits/song-minji',
  },
  {
    id: 'nam-kihyun',
    name: '남기현',
    title: '응급의학과 의사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'melee_dps',
    cost: 3,
    power: 2,
    ability: { type: 'collect', value: 2, description: 'BP +2 수집. SUS -2', onCollect: { sus: -2 } },
    sense: { name: '전장(戰場)의 직감', baseType: '직감', power: 4, flavor: '재고 없음? 헌혈률은 올랐는데 왜 피가 부족하지?', effects: { onPlay: { sus: -2 }, onCollect: { rep: 1 } } },
    flavor: '환자를 살리지 못하는 밤이 늘어간다',
    lore: '응급실은 전쟁터다. 남기현은 밤마다 피를 본다. 수혈이 필요한 환자에게 혈액을 요청하면, 요즘 자꾸 \'재고 없음\'이 뜬다. 이상하다. 헌혈률은 전년 대비 상승했는데, 왜 피가 부족한 걸까. 환자를 살리지 못하는 밤이 늘어나고, 그의 분노도 함께 자란다.',
    portrait: 'assets/portraits/nam-kihyun',
  },
  {
    id: 'baek-sujin',
    name: '백수진',
    title: '감염관리 전문간호사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'battle_support',
    cost: 3,
    power: 2,
    ability: { type: 'research', value: 1, description: '혈액 카드 효율 +1 (이번 턴). SUS -1', onPlay: { sus: -1 } },
    sense: { name: '멸균의 눈', baseType: '혈각', power: 4, flavor: '이 소독제 성분표... 국내 허가를 받지 않은 화합물이에요.', effects: { onPlay: { sus: -2, rep: 2 }, onCollect: { sus: -1, rep: 1 } } },
    flavor: '보이지 않는 전쟁의 파수꾼',
    lore: '감염관리는 눈에 보이지 않는 전쟁이다. 백수진은 센터의 모든 멸균 절차를 감시한다. 그런데 야간에 사용되는 특수 소독제의 성분표가 이상하다. 국내 허가받지 않은 화합물이 포함되어 있고, 발주 기록은 유럽의 한 제약사를 가리킨다. 이름이 없는 회사.',
    portrait: 'assets/portraits/baek-sujin',
  },
  {
    id: 'cha-donghyuk',
    name: '차동혁',
    title: 'IT 보안 담당자',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 3,
    power: 1,
    ability: { type: 'audit', value: 2, description: 'SUS -2. 이벤트 카드 1장 확인' },
    sense: { name: '패턴의 끈', baseType: '감응', power: 4, flavor: '매일 새벽 암호화 데이터가 빈 IP로 전송된다... 뭔가가 있어.', effects: { onPlay: { rep: 2 }, onField: { rep: 1 } } },
    flavor: '숫자 뒤의 진실을 추적하는 자',
    lore: '차동혁의 모니터에는 세계가 숫자로 보인다. 네트워크 트래픽, 접속 로그, 암호화 패킷. 센터 서버에서 매일 새벽 암호화된 데이터가 빈 IP로 전송된다. 추적하면 유럽, 추적하면 소멸. 그는 잠을 줄이고 코드를 파기 시작했다. 뭔가가 있다.',
    portrait: 'assets/portraits/cha-donghyuk',
  },
  {
    id: 'im-yeji',
    name: '임예지',
    title: '혈소판 성분채혈사',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.UNCOMMON,
    role: 'support',
    cost: 2,
    power: 1,
    ability: { type: 'donate', value: 2, description: '혈액 카드 2장 생성. REP +2', onPlay: { rep: 2 } },
    sense: { name: '온기의 손', baseType: '공감', power: 3, flavor: '괜찮아요, 금방 끝나요. ...근데 이 분 혈소판 수치가 왜 이렇게 높지?', effects: { onPlay: { rep: 4 }, onField: { rep: 1 } } },
    flavor: '따뜻한 손, 차가운 의문',
    lore: '혈소판 성분채혈은 시간이 오래 걸린다. 임예지는 그 시간 동안 환자와 이야기한다. 안심시키고, 웃게 하고, 손을 잡아준다. 하지만 특별 예약 헌혈자들은 말이 없다. 차갑고 조용하며, 채혈이 끝나면 감사 인사도 없이 사라진다. 그들의 혈소판 수치는 비정상적으로 높다.',
    portrait: 'assets/portraits/im-yeji',
  },
  {
    id: 'go-seungwoo',
    name: '고승우',
    title: '혈액품질관리 팀장',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.RARE,
    role: 'bruiser',
    cost: 5,
    power: 3,
    ability: { type: 'collect', value: 3, description: 'BP +3 수집. REP +3', onCollect: { rep: 3 } },
    sense: { name: '등급(等級)의 벽', baseType: '예감', power: 6, flavor: '\'등급 S\'는 내 팀을 거치지 않는다. 누가 검사하는 건가?', effects: { onPlay: { sus: -3, rep: 3 }, onCollect: { rep: 1 } } },
    flavor: '혈액 품질에 타협은 없다',
    lore: '혈액 품질에 타협은 없다. 고승우의 팀은 모든 혈액 백을 검사한다. 온도, 색상, 점도, 항체 반응. 완벽한 품질만이 환자에게 갈 수 있다. 하지만 \'등급 S\'로 분류되는 혈액은 그의 팀을 거치지 않는다. 누가 검사하는지, 어디로 가는지 — 그는 알 권리가 있다.',
    portrait: 'assets/portraits/go-seungwoo',
  },
  {
    id: 'hwang-nari',
    name: '황나리',
    title: '센터 부센터장',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.RARE,
    role: 'battle_support',
    cost: 5,
    power: 4,
    ability: { type: 'reputation', value: 6, description: 'REP +6. SUS -3', onPlay: { sus: -3 } },
    sense: { name: '정치의 침묵', baseType: '예감', power: 6, flavor: '떠나면 아무것도 바꿀 수 없으니까.', effects: { onPlay: { sus: -3, rep: 3 }, onCollect: { rep: 1 } } },
    flavor: '미소로 거부하고, 침묵으로 동의한다',
    lore: '부센터장 황나리는 정치의 언어를 안다. 미소로 거부하고, 침묵으로 동의한다. 센터장 박하린의 그림자에서 그녀는 조직의 실질적 운영을 맡고 있다. 카르테인과의 비밀 계약서를 읽은 날, 그녀는 사직서를 쓸까 고민했지만 — 결국 서랍에 넣었다. 떠나면 아무것도 바꿀 수 없으니까.',
    portrait: 'assets/portraits/hwang-nari',
  },
  {
    id: 'moon-taesik',
    name: '문태식',
    title: '백십자재단 이사장',
    faction: FACTIONS.CENTER,
    rarity: RARITIES.LEGENDARY,
    role: 'tank',
    cost: 8,
    power: 5,
    ability: { type: 'reputation', value: 10, description: 'REP +10. 필드 시 SUS -2/턴, BP -1/턴', onField: { sus: -2, bp: -1 } },
    sense: { name: '대부(大父)의 무게', baseType: '예감', power: 9, flavor: '공존이 생명을 살린다고 믿었다. 그 믿음이 흔들리는 밤이 많아지고 있다.', effects: { onPlay: { sus: -5, rep: 5 }, onCollect: { rep: 1 } } },
    flavor: '40년, 수천 명의 생사를 결정한 서명',
    lore: '백십자재단 이사장 문태식. 한국 혈액사업의 대부. 그의 서명 한 줄이 수천 명의 생사를 결정한다. 40년간 혈액사업을 키운 그는 카르테인의 존재를 30년 전부터 알고 있었다. 폭로할 수 있었지만 하지 않았다 — 가문과의 공존이 더 많은 생명을 살린다고 믿었으니까. 그 믿음이 흔들리는 밤이 많아지고 있다.',
    portrait: 'assets/portraits/moon-taesik',
  },
  {
    id: 'cecilia-kartein',
    name: '세실리아 카르테인',
    title: '가문 여주인',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.LEGENDARY,
    role: 'breaker',
    cost: 9,
    power: 6,
    ability: { type: 'request_discount', value: 3, description: '의뢰 이행 비용 -3. 필드 시 SUS +4/턴', onField: { sus: 4 } },
    sense: { name: '제국의 거울', baseType: '혈식', power: 9, flavor: '문화, 금융, 외교 -- 모든 줄은 내 손에서 시작된다.', effects: { onPlay: { sus: 15, rep: -5, bp: -10 }, onField: { sus: 2, rep: -1 } } },
    flavor: '제국의 모든 줄은 그녀의 손에서 시작된다',
    lore: '세실리아 카르테인. 가문의 여주인은 제국의 거울 앞에 선다. 수백 년의 세월이 그녀의 얼굴에는 닿지 않았지만, 그 무게는 눈동자에 고여 있다. 남편 듀크가 서울에서 움직이는 동안, 그녀는 유럽에서 제국을 유지한다. 문화, 금융, 외교 — 모든 줄은 그녀의 손에서 시작된다. 하지만 장녀 이사도라의 야심은 어머니조차 통제할 수 없는 영역에 다다르고 있었다.',
    portrait: 'assets/portraits/cecilia-kartein',
  },
  {
    id: 'madeleine-voss',
    name: '마들렌 보스',
    title: '카르테인 의전관',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'evasive_dps',
    cost: 5,
    power: 3,
    ability: { type: 'request_discount', value: 1, description: '의뢰 이행 비용 -1. SUS +3', onPlay: { sus: 3 } },
    sense: { name: '의전(儀典)의 막', baseType: '혈유', power: 7, flavor: '어떤 문도 내 허락 없이는 열리지 않는다.', effects: { onPlay: { sus: 6, rep: -1, bp: -3 }, onField: { sus: 1 } } },
    flavor: '완벽한 격식 뒤의 피의 의식',
    lore: '카르테인 가문의 의전은 마들렌 보스의 손을 거친다. 초대장 한 장, 좌석 배치 하나에도 수백 년의 격식이 담겨 있다. 서울의 비공식 만찬을 준비하며 그녀는 완벽한 겉모습 뒤에 피의 의식을 숨긴다. 어떤 문도 그녀의 허락 없이는 열리지 않는다.',
    portrait: 'assets/portraits/madeleine-voss',
  },
  {
    id: 'aldric-thorne',
    name: '알드릭 쏜',
    title: '카르테인 경호대장',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'tank',
    cost: 6,
    power: 4,
    ability: { type: 'audit', value: 3, description: 'SUS -3. 필드 시 SUS +2/턴', onField: { sus: 2 } },
    sense: { name: '경호의 흉터', baseType: '혈기', power: 7, flavor: '가문의 안전. 그 이외의 것은 모두 제거 대상이다.', effects: { onPlay: { sus: 3 }, onField: { sus: 1, bp: -1 } } },
    flavor: '흉터 하나하나가 가문을 위한 전투의 증거',
    lore: '알드릭 쏜이 서 있으면 그 뒤에는 아무도 다가가지 못한다. 카르테인 경호대장의 몸에는 지도처럼 흉터가 새겨져 있고, 각각의 흉터는 가문을 위해 치른 전투의 증거다. 서울에서 그의 임무는 단순하다 — 가문의 안전. 그 이외의 것은 모두 제거 대상이다.',
    portrait: 'assets/portraits/aldric-thorne',
  },
  {
    id: 'otto-brandt',
    name: '오토 브란트',
    title: '카르테인 회계사',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.UNCOMMON,
    role: 'support',
    cost: 3,
    power: 2,
    ability: { type: 'request_discount', value: 1, description: '의뢰 이행 비용 -1' },
    sense: { name: '이면의 장부', baseType: '혈맹', power: 4, flavor: '장부는 두 개 -- 하나는 세상에 보여줄 것, 하나는 진실.', effects: { onPlay: { sus: 2, bp: -2 }, onCollect: { bp: 1 } } },
    flavor: '숫자로 거짓말을 만드는 남자',
    lore: '숫자는 거짓말을 하지 않는다. 하지만 오토 브란트는 숫자로 거짓말을 만든다. 카르테인 가문의 회계사로서, 그는 전 세계에 퍼진 혈액 거래의 자금을 세탁한다. 장부는 두 개 — 하나는 세상에 보여줄 것, 하나는 진실. 그의 불안한 눈은 진실의 무게를 견디지 못하고 있다.',
    portrait: 'assets/portraits/otto-brandt',
  },
  {
    id: 'kaspar-wren',
    name: '카스파 렌',
    title: '정보 수집가',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.UNCOMMON,
    role: 'evasive_dps',
    cost: 3,
    power: 2,
    ability: { type: 'audit', value: 2, description: 'SUS -2. 이벤트 카드 1장 확인. SUS +1', onPlay: { sus: 1 } },
    sense: { name: '무형의 얼굴', baseType: '혈향', power: 4, flavor: '그들이 무엇을 알고 있는지, 나는 이미 알고 있다.', effects: { onPlay: { sus: 2 }, onField: { sus: 1 }, onCollect: { bp: -1 } } },
    flavor: '얼굴을 기억하는 사람은 없다',
    lore: '카스파 렌의 얼굴을 기억하는 사람은 없다. 그것이 그의 능력이다. 카르테인의 정보 수집가는 어디에나 있고, 어디에도 없다. 서울의 센터 직원들, 기자들, 경찰들 — 그들이 무엇을 알고 있는지, 그는 이미 파악했다. 보고서는 매일 밤 듀크에게 전달된다.',
    portrait: 'assets/portraits/kaspar-wren',
  },
  {
    id: 'nadia-petrova',
    name: '나디아 페트로바',
    title: '혈액 운반 코디네이터',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 4,
    power: 2,
    ability: { type: 'transport', value: 2, description: '의뢰 이행 시 BP 보너스 +2. SUS +1', onPlay: { sus: 1 } },
    sense: { name: '빙하의 항로', baseType: '혈기', power: 4, flavor: '북극해에서 적도까지. 냉장 컨테이너는 멈추지 않는다.', effects: { onPlay: { sus: 2 }, onField: { sus: 1, bp: -1 } } },
    flavor: '북극해에서 적도까지, 냉장 컨테이너는 멈추지 않는다',
    lore: '북극해에서 적도까지, 나디아 페트로바의 물류 네트워크는 전 세계를 잇는다. 차가운 눈빛과 냉철한 판단으로 그녀는 혈액 운반의 그림자 공급망을 관리한다. 냉장 컨테이너, 위장 화물, 위조 서류 — 모든 것이 그녀의 태블릿 위에서 움직인다.',
    portrait: 'assets/portraits/nadia-petrova',
  },
  {
    id: 'lucien-deveraux',
    name: '루시앙 드보로',
    title: '카르테인 문서위조사',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.UNCOMMON,
    role: 'melee_dps',
    cost: 3,
    power: 2,
    ability: { type: 'convert', value: 1, description: '혈액 카드 1장을 아무 혈액형으로 변환. SUS +1', onPlay: { sus: 1 } },
    sense: { name: '위조의 예술', baseType: '혈맹', power: 4, flavor: '잉크가 마르기 전에 완벽해야 한다.', effects: { onPlay: { sus: 2, bp: -2 }, onCollect: { bp: 1 } } },
    flavor: '잉크가 마르기 전에 완벽해야 한다',
    lore: '루시앙 드보로의 손끝에서 거짓이 진실이 된다. 여권, 의료 면허증, 혈통 증명서 — 무엇이든 만들어낸다. 카르테인 가문이 전 세계에서 합법적으로 존재하기 위해, 그의 기술은 필수다. 서울에서의 임무는 가문의 새로운 신분을 만드는 것. 잉크가 마르기 전에 완벽해야 한다.',
    portrait: 'assets/portraits/lucien-deveraux',
  },
  {
    id: 'marcus-vale',
    name: '마르쿠스 베일',
    title: '새벽의 사냥꾼',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'melee_dps',
    cost: 6,
    power: 4,
    ability: { type: 'collect', value: 4, description: 'BP +4 수집. SUS +3', onPlay: { sus: 3 } },
    sense: { name: '새벽의 포식', baseType: '혈식', power: 7, flavor: '밤이 끝나기 전에, 사냥을 마쳐야 한다.', effects: { onPlay: { sus: 9, rep: -3, bp: -6 }, onField: { sus: 2, rep: -1 } } },
    flavor: '한 번도 실패한 적이 없다 — 아직까지는',
    lore: '새벽의 사냥꾼. 마르쿠스 베일이 움직이면 누군가가 사라진다. 카르테인 가문의 \'문제 해결사\'인 그는 감정 없이 임무를 수행한다. 서울에서 그의 대상은 진실에 너무 가까이 다가간 사람들이다. 한 번도 실패한 적이 없다 — 아직까지는.',
    portrait: 'assets/portraits/marcus-vale',
  },
  {
    id: 'vivienne-la-croix',
    name: '비비엔 라크로아',
    title: '가문 사교계 대리인',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'battle_support',
    cost: 5,
    power: 3,
    ability: { type: 'reputation', value: 5, description: 'REP +5. SUS +3', onPlay: { sus: 3 } },
    sense: { name: '살롱의 유혹', baseType: '혈유', power: 6, flavor: '한 잔의 와인과 한 줄기 미소면 충분해요, 그렇지 않나요?', effects: { onPlay: { sus: 6, rep: -1, bp: -3 }, onField: { sus: 1 } } },
    flavor: '매력적인 웃음 뒤에는 가문을 위한 거래가 있다',
    lore: '샴페인 잔 너머로 비비엔 라크로아는 서울의 사교계를 움직인다. 재벌가의 파티, 대사관의 리셉션 — 그녀가 가는 곳에 문이 열린다. 카르테인 가문이 직접 나설 수 없는 자리에 그녀가 선다. 매력적인 웃음 뒤에는 가문을 위한 거래가 있다.',
    portrait: 'assets/portraits/vivienne-la-croix',
  },
  {
    id: 'nikolai-frost',
    name: '니콜라이 프로스트',
    title: '동유럽 혈액 밀수업자',
    faction: FACTIONS.KARTEIN,
    rarity: RARITIES.RARE,
    role: 'bruiser',
    cost: 5,
    power: 3,
    ability: { type: 'transport', value: 2, description: '의뢰 이행 시 BP 보너스 +2. SUS +2', onPlay: { sus: 2 } },
    sense: { name: '얼음의 밀수', baseType: '혈기', power: 6, flavor: '국경은 단지 숫자일 뿐이다.', effects: { onPlay: { sus: 3 }, onField: { sus: 1, bp: -1 } } },
    flavor: '국경을 넘는 냉장 화물의 비밀',
    lore: '니콜라이 프로스트의 냉장 화물에는 의문을 제기하는 사람이 없다. 동유럽에서 서울까지, 그의 경로를 막을 수 있는 세관은 없다. 군복 위에 모피를 걸치고, 그는 국경을 넘는다. 화물의 내용물은 묻지 않는 것이 규칙이다. 대가는 충분히 지불되었으니까.',
    portrait: 'assets/portraits/nikolai-frost',
  },
  {
    id: 'yoo-minjae',
    name: '유민재',
    title: '택시 기사',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.COMMON,
    role: 'melee_dps',
    cost: 1,
    power: 1,
    ability: { type: 'transport', value: 1, description: '의뢰 이행 시 BP 보너스 +1' },
    sense: { name: '밤의 택시', baseType: '직감', power: 1, flavor: '새벽 3시 정장 외국인... 요금은 10만 원, 거스름돈은 필요 없다고.', effects: { onPlay: { sus: -1 }, onCollect: { rep: 1 } } },
    flavor: '30년간 서울의 밤거리를 달린 남자',
    lore: '밤 택시를 몰면 별일을 다 본다. 유민재는 30년간 서울의 밤거리를 달렸다. 헌혈센터 앞에서 태운 손님 중에 이상한 사람이 많다. 새벽 3시에 정장 차림의 외국인들, 행선지는 항상 \'강남 쪽\'이라고만 한다. 요금은 10만 원짜리로 낸다. 거스름돈은 필요 없다고.',
    portrait: 'assets/portraits/yoo-minjae',
  },
  {
    id: 'bae-jongho',
    name: '배종호',
    title: '퇴직 형사',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.COMMON,
    role: 'tank',
    cost: 2,
    power: 1,
    ability: { type: 'audit', value: 1, description: 'SUS -1. 이벤트 카드 1장 확인' },
    sense: { name: '은퇴의 직감', baseType: '직감', power: 2, flavor: '직감은 속이지 않는다. 혼자 파볼 생각이다.', effects: { onPlay: { sus: -1 }, onCollect: { rep: 1 } } },
    flavor: '30년 형사의 직감은 속이지 않는다',
    lore: '30년 형사 생활의 직감은 배종호를 속이지 않는다. 퇴직 후에도 그는 센터 근처를 산책한다. 실종 신고가 이 동네에서 유난히 많다는 걸 현직 시절에 알았다. 하지만 수사는 항상 윗선에서 막혔다. 이제 자유의 몸이니까, 혼자 파볼 생각이다.',
    portrait: 'assets/portraits/bae-jongho',
  },
  {
    id: 'hong-taejun',
    name: '홍태준',
    title: '열혈 유튜버',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.COMMON,
    role: 'melee_dps',
    cost: 1,
    power: 1,
    ability: { type: 'reputation', value: 3, description: 'REP +3' },
    sense: { name: '렌즈의 직감', baseType: '직감', power: 2, flavor: '\'더 파지 마세요. 위험합니다.\' 조회수가 폭발했다.', effects: { onPlay: { sus: -1 }, onCollect: { rep: 1 } } },
    flavor: '구독자 50만의 센터 잠입 시도',
    lore: '구독자 50만의 유튜버 홍태준. \'센터 내부 잠입 촬영\'을 기획했다가 경비에게 쫓겨났다. 하지만 그날 찍은 영상에 이상한 것이 잡혔다 — 새벽 배경에 움직이는 그림자들. 댓글에 누군가 썼다. \'더 파지 마세요. 위험합니다.\' 조회수가 폭발했다.',
    portrait: 'assets/portraits/hong-taejun',
  },
  {
    id: 'kang-mirae',
    name: '강미래',
    title: '사회복지사',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.UNCOMMON,
    role: 'support',
    cost: 3,
    power: 2,
    ability: { type: 'research', value: 1, description: '혈액 카드 효율 +1 (이번 턴). REP +2', onPlay: { rep: 2 } },
    sense: { name: '역학의 눈', baseType: '예감', power: 3, flavor: '개인의 문제가 아니라 지역의 문제야. 패턴이 보인다.', effects: { onPlay: { sus: -2, rep: 2 }, onCollect: { rep: 1 } } },
    flavor: '사람의 말 뒤에 숨은 진실을 읽는다',
    lore: '사회복지사 강미래는 사람의 말 뒤에 숨은 진실을 읽는다. 헌혈센터 인근 주민들의 상담을 맡으면서, 공통된 호소를 발견했다. 원인 모를 피로, 기억의 공백, 밤에 들리는 소리. 개인의 문제가 아니라 지역의 문제다. 그녀는 역학 패턴을 그려보기 시작했다.',
    portrait: 'assets/portraits/kang-mirae',
  },
  {
    id: 'seo-pilsung',
    name: '서필성',
    title: '국과수 법의학자',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.UNCOMMON,
    role: 'ranged_dps',
    cost: 4,
    power: 2,
    ability: { type: 'research', value: 2, description: '혈액 카드 효율 +2 (이번 턴). SUS -1', onPlay: { sus: -1 } },
    sense: { name: '혈흔의 언어', baseType: '혈각', power: 4, flavor: 'DNA는 인간인데 세포 구조가... 교과서와 다르다.', effects: { onPlay: { sus: -2, rep: 2 }, onCollect: { sus: -1, rep: 1 } } },
    flavor: '피는 증거일 뿐이다. 감정도, 공포도 없다',
    lore: '피는 서필성에게 증거일 뿐이다. 감정도, 공포도 없다. 국과수 법의학자의 현미경 아래에서 혈흔은 이야기를 시작한다. 최근 의뢰받은 사건의 혈흔이 이상하다 — DNA는 인간인데, 세포 구조가 교과서와 다르다. 논문을 쓸까, 말까. 학계가 믿어줄 리가 없다.',
    portrait: 'assets/portraits/seo-pilsung',
  },
  {
    id: 'won-hyunsoo',
    name: '원현수',
    title: '보험사 조사관',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.UNCOMMON,
    role: 'bruiser',
    cost: 3,
    power: 2,
    ability: { type: 'audit', value: 2, description: 'SUS -2. 이벤트 카드 1장 확인' },
    sense: { name: '보험의 감', baseType: '예감', power: 4, flavor: '단서를 따라가면 항상 같은 곳에 닿는다 -- 센터의 야간 부서.', effects: { onPlay: { sus: -2, rep: 2 }, onCollect: { rep: 1 } } },
    flavor: '보험금 청구 패턴이 진실을 말한다',
    lore: '보험금 청구 패턴에서 원현수는 이상을 감지했다. 헌혈센터 인근 병원의 수혈 관련 보험 청구가 급증하고 있는데, 실제 수혈 기록과 맞지 않는다. 누군가 혈액을 빼돌리고 보험금으로 세탁하고 있다. 단서를 따라가면 항상 같은 곳에 닿는다 — 센터의 야간 부서.',
    portrait: 'assets/portraits/won-hyunsoo',
  },
  {
    id: 'ryu-seungmin',
    name: '류승민',
    title: '경찰청 사이버수사대',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.RARE,
    role: 'evasive_dps',
    cost: 5,
    power: 3,
    ability: { type: 'audit', value: 4, description: 'SUS -4. 이벤트 카드 1장 확인' },
    sense: { name: '사이버의 끝', baseType: '직감', power: 6, flavor: '디지털 발자국은 희미하지만, 나는 포기하지 않는다.', effects: { onPlay: { sus: -3 }, onCollect: { rep: 1 } } },
    flavor: '디지털 발자국을 추적하는 사이버 수사관',
    lore: '사이버수사대 류승민은 다크웹에서 이상한 거래를 추적하고 있다. \'레드 마켓\'이라 불리는 폐쇄적 플랫폼에서 혈액이 거래된다. 비트코인이 아닌 독자적 암호화폐로. 서버를 추적하면 유럽과 서울을 오간다. 디지털 발자국은 희미하지만, 류승민은 포기하지 않는다.',
    portrait: 'assets/portraits/ryu-seungmin',
  },
  {
    id: 'jo-eunyoung',
    name: '조은영',
    title: '국정원 요원',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.RARE,
    role: 'bruiser',
    cost: 5,
    power: 4,
    ability: { type: 'audit', value: 5, description: 'SUS -5. 이벤트 카드 2장 확인' },
    sense: { name: '극비의 눈', baseType: '예감', power: 7, flavor: '이 나라의 혈액이 외부 세력에 통제되는 것을 용납할 수 없다.', effects: { onPlay: { sus: -3, rep: 3 }, onCollect: { rep: 1 } } },
    flavor: '그녀의 존재를 아는 사람은 없다',
    lore: '국정원 요원 조은영. 그녀의 존재를 아는 사람은 없고, 알아서도 안 된다. 카르테인 가문에 대한 정보 파일이 그녀의 책상 위에 있다 — \'등급: 극비\'. 외교적으로 손댈 수 없는 대상이지만, 이 나라의 혈액이 외부 세력에 의해 통제되는 것을 그녀는 용납할 수 없다.',
    portrait: 'assets/portraits/jo-eunyoung',
  },
  {
    id: 'priest-gabriel',
    name: '가브리엘 신부',
    title: '바티칸 조사관',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.RARE,
    role: 'bruiser',
    cost: 4,
    power: 3,
    ability: { type: 'research', value: 2, description: '혈액 카드 효율 +2 (이번 턴). REP +3', onPlay: { rep: 3 } },
    sense: { name: '십자가의 빛', baseType: '투지', power: 7, flavor: '신앙과 현실 사이에서, 나는 증거를 가져갈 준비가 되어 있다.', effects: { onPlay: { rep: 3 }, onCollect: { rep: 1 } } },
    flavor: '십자가를 쥔 손은 떨리지 않는다',
    lore: '가브리엘 신부는 바티칸의 비밀 기록보관소에서 온다. 수백 년 전부터 교회가 추적해온 \'밤의 혈족\'에 대한 기록을 가지고 서울에 도착했다. 십자가를 쥔 손은 떨리지 않는다. 신앙과 현실 사이에서, 그는 악을 목격하고 증거를 가져갈 준비가 되어 있다.',
    portrait: 'assets/portraits/priest-gabriel',
  },
  {
    id: 'commissioner-park',
    name: '박총경',
    title: '서울경찰청 수사본부장',
    faction: FACTIONS.NEUTRAL,
    rarity: RARITIES.LEGENDARY,
    role: 'breaker',
    cost: 7,
    power: 5,
    ability: { type: 'audit', value: 8, description: 'SUS -8. 필드 시 REP +1/턴, BP -1/턴', onField: { rep: 1, bp: -1 } },
    sense: { name: '수사의 벽', baseType: '투지', power: 9, flavor: '법 위에 있는 자는 없다. 누구든.', effects: { onPlay: { rep: 5 }, onCollect: { rep: 1 } } },
    flavor: '법 위에 있는 자는 없어야 한다',
    lore: '박총경의 수사 게시판에는 빨간 실이 엉켜 있다. 헌혈센터, 실종자, 외교 차량, 밤의 목격담. 모든 것이 연결되어 있다. 증거도 있고, 인력도 있다. 하지만 청와대에서 내려온 한 통의 전화가 모든 것을 멈추게 했다. \'국익을 위해 중단하라.\' 총경의 주먹이 떨린다. 법 위에 있는 자는 없어야 하는데.',
    portrait: 'assets/portraits/commissioner-park',
  },
];

export const STORY_BEATS = [
  { trigger: 'turn-1', text: '백십자재단 혈연센터에 첫 출근하는 날. 밝은 형광등 아래, 모든 것이 정상적으로 보인다... 아직은.' },
  { trigger: 'first-request', text: '비밀 연락망을 통해 첫 의뢰서가 도착했다. 카르테인 가문의 혈액관리국, 그 이름만으로도 무게가 느껴진다.' },
  { trigger: 'first-complete', text: '"훌륭하군." 짧은 메모가 도착했다. 카르테인 집사 빅토르의 필체.' },
  { trigger: 'turn-5', text: '센터 운영이 안정궤도에 올랐다. 하지만 밤이 되면 다른 일이 시작된다.' },
  { trigger: 'sus-50', text: '보건당국에서 "야간 혈액 사용량 이상"을 문의해왔다. 서류를 조작해야 할지도 모른다.' },
  { trigger: 'sus-80', text: '기자가 센터 주변을 어슬렁거린다. 누군가 제보한 걸까? 시간이 얼마 남지 않았다.' },
  { trigger: 'rep-low', text: '헌혈자 수가 급감하고 있다. 센터의 평판이 흔들리면 모든 것이 무너질 수 있다.' },
  { trigger: 'final-request', text: '마지막 의뢰. 이것만 완수하면 카르테인과의 거래가 끝난다. 아니, 정말로 끝날까?' },
  { trigger: 'win', text: '카르테인 가문의 의뢰를 모두 완수했다. 듀크가 보낸 봉인된 편지: "당신은 가문의 친구입니다. 영원히."' },
  { trigger: 'lose-sus', text: '새벽 4시, 특수수사대가 센터에 도착했다. 냉장고 뒤의 비밀 통로가 발견되었다...' },
  { trigger: 'lose-rep', text: '마지막 헌혈자가 떠났다. 텅 빈 대기실에 형광등만 깜빡인다.' },
];

export function createBloodCard(bloodType) {
  return {
    id: `blood-${bloodType}-${Date.now()}`,
    type: 'blood',
    bloodType,
    value: 1,
    name: `${bloodType}형 혈액`,
    description: `${bloodType}형 혈액 1단위`,
  };
}

export function createRequestCard(id, requirements, reward, penalty) {
  return {
    id,
    type: 'request',
    name: `카르테인 의뢰 #${id}`,
    requirements,
    reward,
    penalty,
    turnsLeft: 3,
  };
}

export const STARTER_REQUESTS = [
  createRequestCard('req-1', { A: 2 }, { bp: 5 }, { sus: 10 }),
  createRequestCard('req-2', { B: 1, O: 1 }, { bp: 4, rep: 3 }, { sus: 8 }),
  createRequestCard('req-3', { O: 3 }, { bp: 8 }, { sus: 15 }),
  createRequestCard('req-4', { A: 1, B: 1, AB: 1 }, { bp: 10, rep: 5 }, { sus: 12 }),
  createRequestCard('req-5', { AB: 2, O: 2 }, { bp: 15, rep: 10 }, { sus: 20, rep: -10 }),
];

export const EVENTS = [
  { id: 'evt-campaign', name: '헌혈 캠페인 성공', effect: { rep: 5, bp: 3 }, description: '백십자재단 캠페인이 성공적! REP+5, BP+3' },
  { id: 'evt-inspection', name: '보건당국 점검', effect: { sus: -5, rep: -3 }, description: '정기 점검 통과. SUS-5, REP-3' },
  { id: 'evt-shortage', name: '혈액 부족 사태', effect: { bp: -3, rep: 5 }, description: '혈액 부족으로 긴급 모집. BP-3, REP+5' },
  { id: 'evt-leak', name: '내부 정보 유출', effect: { sus: 8 }, description: '누군가 야간 활동을 목격. SUS+8' },
  { id: 'evt-donation-day', name: '세계 헌혈의 날', effect: { bp: 5, rep: 5 }, description: '특별 행사! BP+5, REP+5' },
  { id: 'evt-blackout', name: '정전 사고', effect: { bp: -2, sus: 3 }, description: '냉장고 일시 정지. BP-2, SUS+3' },
];

export const DILEMMA_EVENTS = [
  {
    id: 'dil-reporter', name: '기자의 취재 요청',
    narration: '김서하 기자가 센터의 야간 운영에 대해 취재를 요청한다. 거절하면 의심을 살 수 있고, 수락하면 비밀이 노출될 위험이 있다.',
    choices: [
      { label: '취재 수락 — 투명성 어필', desc: 'REP +8, SUS +6', effect: { rep: 8, sus: 6 } },
      { label: '정중히 거절 — 비밀 유지', desc: 'SUS -3, REP -4', effect: { sus: -3, rep: -4 } },
    ],
  },
  {
    id: 'dil-bribe', name: '보건 조사관의 암시',
    narration: '장현우 조사관이 점검 중 수상한 냉장고를 발견했다. 그는 미묘하게 "해결 방법"을 암시한다.',
    choices: [
      { label: '뇌물 제공 — 눈 감아달라', desc: 'BP -5, SUS -10', effect: { bp: -5, sus: -10 } },
      { label: '정면 돌파 — 규정대로', desc: 'REP +5, SUS +8', effect: { rep: 5, sus: 8 } },
    ],
  },
  {
    id: 'dil-overtime', name: '야근 헌혈자 발견',
    narration: '최민서가 센터 폐장 후에도 남아있다. 추가 헌혈을 받으면 혈액을 확보할 수 있지만, 건강 문제가 생기면...',
    choices: [
      { label: '추가 채혈 — 혈액 확보 우선', desc: 'BP +6, REP -5', effect: { bp: 6, rep: -5 } },
      { label: '귀가 권유 — 안전 우선', desc: 'REP +4, BP -2', effect: { rep: 4, bp: -2 } },
    ],
  },
  {
    id: 'dil-night-delivery', name: '새벽 특별 배송',
    narration: '정우진이 새벽 4시에 카르테인 가문용 "특별 혈액"을 배송해야 한다. 경로가 두 곳이다.',
    choices: [
      { label: '지름길 — 빠르지만 CCTV 구간', desc: 'BP +4, SUS +5', effect: { bp: 4, sus: 5 } },
      { label: '우회로 — 안전하지만 손실 있음', desc: 'BP +1, SUS -2', effect: { bp: 1, sus: -2 } },
    ],
  },
  {
    id: 'dil-intern', name: '실습생의 질문',
    narration: '박은지 실습생이 야간 혈액 처리량이 비정상적으로 많다며 질문한다. 호기심 많은 눈이 날카롭다.',
    choices: [
      { label: '비밀에 끌어들이기', desc: 'SUS -5, REP -3 (동료 확보)', effect: { sus: -5, rep: -3 } },
      { label: '모른 척 넘어가기', desc: 'SUS +4 (의심 증가)', effect: { sus: 4 } },
    ],
  },
  {
    id: 'dil-blood-expire', name: '혈액 유통기한 임박',
    narration: '냉장고 속 혈액 팩 다수가 유통기한이 내일이다. 폐기하면 손실이 크고, 라벨을 바꾸면...',
    choices: [
      { label: '라벨 교체 — 혈액 보존', desc: 'BP +5, SUS +7, REP -3', effect: { bp: 5, sus: 7, rep: -3 } },
      { label: '정규 폐기 — 원칙 준수', desc: 'BP -4, REP +3', effect: { bp: -4, rep: 3 } },
    ],
  },
  {
    id: 'dil-kartein-order', name: '카르테인의 긴급 요청',
    narration: '카르테인 듀크가 "특별한 혈액"을 긴급 요청한다. 공식 절차를 무시해야 빠르게 전달할 수 있다.',
    choices: [
      { label: '즉시 전달 — 가문의 신뢰', desc: 'BP +8, SUS +10', effect: { bp: 8, sus: 10 } },
      { label: '공식 절차 고수', desc: 'REP +3, SUS +3', effect: { rep: 3, sus: 3 } },
    ],
  },
  {
    id: 'dil-volunteer', name: '봉사자의 SNS',
    narration: '한소율이 센터에서 찍은 셀카를 SNS에 올리려 한다. 배경에 야간 작업 장면이 살짝 보인다.',
    choices: [
      { label: '허용 — 홍보 효과 기대', desc: 'REP +6, SUS +5', effect: { rep: 6, sus: 5 } },
      { label: '삭제 요청 — 리스크 차단', desc: 'SUS -2, REP -2', effect: { sus: -2, rep: -2 } },
    ],
  },
  {
    id: 'dil-anonymous-tip', name: '익명 제보 전화',
    narration: '보건당국에 "혈연센터의 야간 활동이 수상하다"는 익명 제보가 접수되었다는 소식이 들어온다.',
    choices: [
      { label: '선제 대응 — 자진 점검 요청', desc: 'SUS -8, BP -3, REP +2', effect: { sus: -8, bp: -3, rep: 2 } },
      { label: '무시하고 잠적', desc: 'SUS +3', effect: { sus: 3 } },
    ],
  },
  {
    id: 'dil-research', name: '윤채아의 연구 제안',
    narration: '윤채아가 특이한 혈액 패턴을 발견했다며 심층 연구를 제안한다. 연구 결과가 밖으로 새면 위험할 수 있다.',
    choices: [
      { label: '연구 승인 — 데이터 확보', desc: 'BP +4, SUS +6', effect: { bp: 4, sus: 6 } },
      { label: '연구 보류 — 안전 우선', desc: 'REP +2, SUS -2', effect: { rep: 2, sus: -2 } },
    ],
  },
  {
    id: 'dil-police', name: '순찰 경찰의 방문',
    narration: '심야에 센터 불빛을 보고 순찰 경관이 방문했다. 문을 열어야 하나?',
    choices: [
      { label: '문을 열고 응대', desc: 'SUS +5, REP +3 (협조적)', effect: { sus: 5, rep: 3 } },
      { label: '불을 끄고 숨기', desc: 'SUS -3, REP -2', effect: { sus: -3, rep: -2 } },
    ],
  },
  {
    id: 'dil-competitor', name: '경쟁 센터의 제안',
    narration: '인근 혈액원에서 "혈액 교환 협정"을 제안한다. 거래하면 혈액을 얻지만, 우리의 운영 방식이 노출될 수 있다.',
    choices: [
      { label: '협정 체결 — 혈액 확보', desc: 'BP +6, SUS +4', effect: { bp: 6, sus: 4 } },
      { label: '거절 — 독립 운영', desc: 'REP +2', effect: { rep: 2 } },
    ],
  },
];

export const EQUIPMENT = [
  { id: 'eq-centrifuge', name: '고속 원심분리기', cost: 4, effect: { collectBonus: 1 }, description: '매 턴 BP 수집량 +1' },
  { id: 'eq-fridge', name: '특수 냉장고', cost: 3, effect: { bloodCapacity: 2 }, description: '혈액 보관 한도 +2' },
  { id: 'eq-lounge', name: '프리미엄 대기실', cost: 5, effect: { repBonus: 2 }, description: '매 턴 REP +2' },
  { id: 'eq-cctv', name: '위장 CCTV', cost: 4, effect: { susReduction: 1 }, description: '매 턴 SUS -1' },
];

export const COMBO_BONUSES = {
  center: [
    { threshold: 3, label: '팀워크', effects: { bpBonus: 1 }, description: '센터 3+ 시너지: BP 수집 +1' },
    { threshold: 4, label: '완벽한 운영', effects: { repBonus: 2 }, description: '센터 4+ 시너지: REP +2' },
  ],
  kartein: [
    { threshold: 2, label: '어둠의 결속', effects: { susReduction: 1 }, description: '카르테인 2+ 시너지: SUS -1' },
    { threshold: 3, label: '밤의 지배', effects: { bpBonus: 1 }, description: '카르테인 3+ 시너지: BP +1' },
  ],
  neutral: [
    { threshold: 2, label: '네트워크', effects: { bloodCards: 1 }, description: '비소속 2+ 시너지: 혈액 +1' },
    { threshold: 3, label: '사회적 유대', effects: { repBonus: 1 }, description: '비소속 3+ 시너지: REP +1' },
  ],
};

export function generateRandomRequest(requestNum, turn) {
  const types = [...BLOOD_TYPES];
  const unitCount = Math.ceil(requestNum * 0.8) + 1;
  const typeCount = Math.min(1 + Math.floor(requestNum / 3), 3);
  const shuffledTypes = types.sort(() => Math.random() - 0.5);
  const requirements = {};
  for (let t = 0; t < typeCount; t++) {
    requirements[shuffledTypes[t]] = 0;
  }
  const keys = Object.keys(requirements);
  for (let i = 0; i < unitCount; i++) {
    requirements[keys[i % keys.length]]++;
  }
  const totalNeeded = Object.values(requirements).reduce((a, b) => a + b, 0);
  const bpReward = 5 + totalNeeded * 3 + Math.floor(requestNum * 2);
  const repReward = requestNum >= 2 ? Math.floor(requestNum * 2) : 0;
  const susPenalty = 4 + requestNum * 2;

  return {
    id: `req-${requestNum}-t${turn}`,
    type: 'request',
    name: `카르테인 의뢰 #${requestNum}`,
    requirements,
    reward: { bp: bpReward, ...(repReward > 0 ? { rep: repReward } : {}) },
    penalty: { sus: susPenalty },
    turnsLeft: Math.max(2, 4 - Math.floor(requestNum / 4)),
  };
}
